FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_API_URL

COPY package*.json ./
COPY client/package*.json ./client/

RUN npm ci --workspace client --include-workspace-root

COPY client ./client

WORKDIR /app/client

ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:1.27-alpine AS runner

COPY --from=build /app/client/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]