server {
  listen 4000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ^~ /docs {
    proxy_pass http://server:4001;
  }

  location = /docs-json {
    proxy_pass http://server:4001/docs-json;
  }

  location ^~ /sql {
    proxy_pass http://server:4001;
  }
}
